package vista;

import modelo.FuncionesUtiles;
import java.awt.Color;
import java.text.DateFormat;
import java.time.LocalDateTime;
import java.util.Date;

public class PanelInformacionArriba extends javax.swing.JPanel {

    /**
     * Creates new form PanelInformacionArriba
     */
    public PanelInformacionArriba() {
        initComponents();
        inicializar();
    }
    
    private void inicializar(){
        this.setBounds(0, 0, 1000, 110);
        this.setBackground(Color.WHITE);
        
        FuncionesUtiles tools = new FuncionesUtiles();
        jLabelHoraActual.setText(tools.getHora());
        jLabelFechaActual.setText(tools.getFecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenida = new javax.swing.JLabel();
        jLabelFechaActual = new javax.swing.JLabel();
        jLabelHoraActual = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 110));
        setPreferredSize(new java.awt.Dimension(1000, 110));

        jLabelBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenida.setText("Bienvenido PENDIENTE");

        jLabelFechaActual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFechaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFechaActual.setText("28 de Noviembre del 2022");

        jLabelHoraActual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelHoraActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHoraActual.setText("17:17");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHoraActual, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFechaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelHoraActual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelFechaActual;
    private javax.swing.JLabel jLabelHoraActual;
    // End of variables declaration//GEN-END:variables
}
